### ISSUE TITLE
Failure upon example introspection query

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1151]
An example introspection query taken from the GraphQL 2021 spec. It requests the name of the `User` type and the name and type of all the fields in the `User` type. It asks for the name and type of each field using the `fields` field and the `name` and `type` fields of each field respectively.
```gql
{
  __type(name: "User") {
    name
    fields {
      name
      type {
        name
      }
    }
  }
}
```

Over DB using schema:
```gql
type User {
  ID: String
  Name: String
}
```

Results in goroutine crash:

```
2023/02/24 18:18:21 http: panic serving 127.0.0.1:61693: interface conversion: graphql.Type is *graphql.NonNull, not *graphql.Object
goroutine 487 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1850 +0xb0
panic({0x101f6be80, 0x14000c8a120})
	runtime/panic.go:890 +0x258
github.com/sourcenetwork/defradb/request/graphql/parser.typeFromFieldDef(0x14000640720?)
	github.com/sourcenetwork/defradb/request/graphql/parser/request.go:238 +0xe8
github.com/sourcenetwork/defradb/request/graphql/parser.parseSelect({0x14000640720, {0x14000010210, 0x1, 0x1}, 0x1400016bc30, 0x14000992b00, 0x0, 0x14000640a80, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/query.go:185 +0x6c8
github.com/sourcenetwork/defradb/request/graphql/parser.parseSelectFields({0x14000640720, {0x14000010210, 0x1, 0x1}, 0x1400016bc30, 0x14000992b00, 0x0, 0x14000640a80, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/request.go:181 +0x2a0
github.com/sourcenetwork/defradb/request/graphql/parser.parseSelect({0x14000640720, {0x14000010210, 0x1, 0x1}, 0x1400016bc30, 0x14000992b00, 0x0, 0x14000640a80, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/query.go:190 +0x718
github.com/sourcenetwork/defradb/request/graphql/parser.parseQueryOperationDefinition({0x14000640720, {0x14000010210, 0x1, 0x1}, 0x1400016bc30, 0x14000992b00, 0x0, 0x14000640a80, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/query.go:65 +0x368
github.com/sourcenetwork/defradb/request/graphql/parser.ParseRequest({0x14000640720, {0x14000010210, 0x1, 0x1}, 0x1400016bc30, 0x14000992b00, 0x0, 0x14000640a80, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/request.go:45 +0x298
github.com/sourcenetwork/defradb/request/graphql.(*parser).Parse(0x14000ec2930, {0x14000e5e150?, 0x13319c128?})
	github.com/sourcenetwork/defradb/request/graphql/parser.go:93 +0x230
github.com/sourcenetwork/defradb/db.(*db).ExecRequest(0x140001681b0, {0x102192a20?, 0x140078d8ba0}, {0x14000e5e150, 0x6a})
	github.com/sourcenetwork/defradb/db/request.go:37 +0x118
github.com/sourcenetwork/defradb/api/http.execGQLHandler({0x10218f3f0, 0x1400003d680}, 0x140078da700)
	github.com/sourcenetwork/defradb/api/http/handlerfuncs.go:147 +0x5a0
github.com/sourcenetwork/defradb/api/http.(*handler).handle.func1({0x10218f3f0, 0x1400003d680}, 0x140078da600)
	github.com/sourcenetwork/defradb/api/http/handler.go:86 +0x2d0
net/http.HandlerFunc.ServeHTTP(0x101f47700?, {0x10218f3f0?, 0x1400003d680?}, 0x140005a21a5?)
	net/http/server.go:2109 +0x38
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x1400059be60, {0x10218f3f0, 0x1400003d680}, 0x140078da600)
	github.com/go-chi/chi/v5@v5.0.8/mux.go:444 +0x22c
net/http.HandlerFunc.ServeHTTP(0x14000b1f9c8?, {0x10218f3f0?, 0x1400003d680?}, 0x30?)
	net/http/server.go:2109 +0x38
github.com/sourcenetwork/defradb/api/http.loggerMiddleware.func1({0x102190e60?, 0x14000b7a000}, 0x140078da600)
	github.com/sourcenetwork/defradb/api/http/logger.go:57 +0xbc
net/http.HandlerFunc.ServeHTTP(0x102192978?, {0x102190e60?, 0x14000b7a000?}, 0x102c174e0?)
	net/http/server.go:2109 +0x38
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x1400059be60, {0x102190e60, 0x14000b7a000}, 0x140078da500)
	github.com/go-chi/chi/v5@v5.0.8/mux.go:90 +0x2d8
net/http.serverHandler.ServeHTTP({0x10218acb8?}, {0x102190e60, 0x14000b7a000}, 0x140078da500)
	net/http/server.go:2947 +0x2c4
net/http.(*conn).serve(0x14000711720, {0x102192a20, 0x140009721b0})
	net/http/server.go:1991 +0x560
created by net/http.(*Server).Serve
	net/http/server.go:3102 +0x444
```

Ideally introspection queries like that shouldn't crash, even though they might ask for information we don't support.

On DefraDB develop (https://github.com/sourcenetwork/defradb/commit/f8ebc86ee949e172e8942587bbca4aa02716eb14) at time of issue

**Comment by orpheuslummis** [comment]
fixed by https://github.com/sourcenetwork/defradb/pull/1255
