### ISSUE TITLE
GraphQL variables support

### ISSUE THREAD

**Issue by orpheuslummis** [sourcenetwork/defradb#1441]
One feature of GraphQL is variables https://graphql.org/learn/queries/#variables.

I used the following query, with version `defradb dev-develop (07d24020 2023-04-27) built with Go 1.19.8 darwin/arm64`, with the `Doc` type loaded.

```
query MyQuery($cid: String) {
    Doc(cid: $cid) {
      _version {
          schemaVersionId
        }
      }
}
```

Which results in the following.
Note that it doesn't crash defradb, just the involved coroutine(s).

```
goroutine 618 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1850 +0xb0
panic({0x103d3fd20, 0x14001be6c30})
	runtime/panic.go:890 +0x258
github.com/sourcenetwork/defradb/request/graphql/parser.parseSelect({0x140010f0210, {0x14000a380c0, 0x1, 0x1}, 0x14000aca420, 0x14000aca4d0, 0x0, 0x140010f02d0, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/query.go:138 +0xc60
github.com/sourcenetwork/defradb/request/graphql/parser.parseQueryOperationDefinition({0x140010f0210, {0x14000a380c0, 0x1, 0x1}, 0x14000aca420, 0x14000aca4d0, 0x0, 0x140010f02d0, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/query.go:65 +0x368
github.com/sourcenetwork/defradb/request/graphql/parser.ParseRequest({0x140010f0210, {0x14000a380c0, 0x1, 0x1}, 0x14000aca420, 0x14000aca4d0, 0x0, 0x140010f02d0, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/request.go:45 +0x298
github.com/sourcenetwork/defradb/request/graphql.(*parser).Parse(0x14001b95f90?, 0x140008cb180?)
	github.com/sourcenetwork/defradb/request/graphql/parser.go:98 +0xc8
github.com/sourcenetwork/defradb/db.(*db).execRequest(0x140005fc2d0, {0x103f71bc0?, 0x14001b97830}, {0x140008cb180, 0xd3}, {0x103f7f380?, 0x14001be4000})
	github.com/sourcenetwork/defradb/db/request.go:33 +0x12c
github.com/sourcenetwork/defradb/db.(*implicitTxnDB).ExecRequest(0x1400051e558, {0x103f71bc0, 0x14001b97830}, {0x140008cb180, 0xd3})
	github.com/sourcenetwork/defradb/db/txn_db.go:44 +0x178
github.com/sourcenetwork/defradb/api/http.execGQLHandler({0x103f6e3f0, 0x1400c46cfc0}, 0x14000259700)
	github.com/sourcenetwork/defradb/api/http/handlerfuncs.go:148 +0x594
github.com/sourcenetwork/defradb/api/http.(*handler).handle.func1({0x103f6e3f0, 0x1400c46cfc0}, 0x14000259600)
	github.com/sourcenetwork/defradb/api/http/handler.go:86 +0x2d0
net/http.HandlerFunc.ServeHTTP(0x103d1b320?, {0x103f6e3f0?, 0x1400c46cfc0?}, 0x14000202705?)
	net/http/server.go:2109 +0x38
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x140005b02a0, {0x103f6e3f0, 0x1400c46cfc0}, 0x14000259600)
	github.com/go-chi/chi/v5@v5.0.8/mux.go:444 +0x22c
net/http.HandlerFunc.ServeHTTP(0x140011f79c8?, {0x103f6e3f0?, 0x1400c46cfc0?}, 0x30?)
	net/http/server.go:2109 +0x38
github.com/sourcenetwork/defradb/api/http.loggerMiddleware.func1({0x103f6fe60?, 0x14000a0a000}, 0x14000259600)
	github.com/sourcenetwork/defradb/api/http/logger.go:57 +0xbc
net/http.HandlerFunc.ServeHTTP(0x103f71b18?, {0x103f6fe60?, 0x14000a0a000?}, 0x104a1d070?)
	net/http/server.go:2109 +0x38
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x140005b02a0, {0x103f6fe60, 0x14000a0a000}, 0x14000259500)
	github.com/go-chi/chi/v5@v5.0.8/mux.go:90 +0x2d8
net/http.serverHandler.ServeHTTP({0x103f69b28?}, {0x103f6fe60, 0x14000a0a000}, 0x14000259500)
	net/http/server.go:2947 +0x2c4
net/http.(*conn).serve(0x14000acd220, {0x103f71bc0, 0x14000a40c30})
	net/http/server.go:1991 +0x560
created by net/http.(*Server).Serve
	net/http/server.go:3102 +0x444
2023/05/01 19:31:20 http: panic serving 127.0.0.1:61872: interface conversion: ast.Value is *ast.Variable, not *ast.StringValue
goroutine 687 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1850 +0xb0
panic({0x103d3fd20, 0x14001d055c0})
	runtime/panic.go:890 +0x258
github.com/sourcenetwork/defradb/request/graphql/parser.parseSelect({0x140010f0210, {0x14000a380c0, 0x1, 0x1}, 0x14000aca420, 0x14000aca4d0, 0x0, 0x140010f02d0, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/query.go:138 +0xc60
github.com/sourcenetwork/defradb/request/graphql/parser.parseQueryOperationDefinition({0x140010f0210, {0x14000a380c0, 0x1, 0x1}, 0x14000aca420, 0x14000aca4d0, 0x0, 0x140010f02d0, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/query.go:65 +0x368
github.com/sourcenetwork/defradb/request/graphql/parser.ParseRequest({0x140010f0210, {0x14000a380c0, 0x1, 0x1}, 0x14000aca420, 0x14000aca4d0, 0x0, 0x140010f02d0, 0x0, {0x0, ...}}, ...)
	github.com/sourcenetwork/defradb/request/graphql/parser/request.go:45 +0x298
github.com/sourcenetwork/defradb/request/graphql.(*parser).Parse(0x14001d18000?, 0x14001d16000?)
	github.com/sourcenetwork/defradb/request/graphql/parser.go:98 +0xc8
github.com/sourcenetwork/defradb/db.(*db).execRequest(0x140005fc2d0, {0x103f71bc0?, 0x14001d041e0}, {0x14001d16000, 0xd3}, {0x103f7f380?, 0x14001d18050})
	github.com/sourcenetwork/defradb/db/request.go:33 +0x12c
github.com/sourcenetwork/defradb/db.(*implicitTxnDB).ExecRequest(0x1400051e558, {0x103f71bc0, 0x14001d041e0}, {0x14001d16000, 0xd3})
	github.com/sourcenetwork/defradb/db/txn_db.go:44 +0x178
github.com/sourcenetwork/defradb/api/http.execGQLHandler({0x103f6e3f0, 0x14000742020}, 0x140000a6200)
	github.com/sourcenetwork/defradb/api/http/handlerfuncs.go:148 +0x594
github.com/sourcenetwork/defradb/api/http.(*handler).handle.func1({0x103f6e3f0, 0x14000742020}, 0x140000a6100)
	github.com/sourcenetwork/defradb/api/http/handler.go:86 +0x2d0
net/http.HandlerFunc.ServeHTTP(0x103d1b320?, {0x103f6e3f0?, 0x14000742020?}, 0x14000a48045?)
	net/http/server.go:2109 +0x38
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x140005b02a0, {0x103f6e3f0, 0x14000742020}, 0x140000a6100)
	github.com/go-chi/chi/v5@v5.0.8/mux.go:444 +0x22c
net/http.HandlerFunc.ServeHTTP(0x1400071a9c8?, {0x103f6e3f0?, 0x14000742020?}, 0x30?)
	net/http/server.go:2109 +0x38
github.com/sourcenetwork/defradb/api/http.loggerMiddleware.func1({0x103f6fe60?, 0x14001d14000}, 0x140000a6100)
	github.com/sourcenetwork/defradb/api/http/logger.go:57 +0xbc
net/http.HandlerFunc.ServeHTTP(0x103f71b18?, {0x103f6fe60?, 0x14001d14000?}, 0x104a1d070?)
	net/http/server.go:2109 +0x38
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x140005b02a0, {0x103f6fe60, 0x14001d14000}, 0x140000a6000)
	github.com/go-chi/chi/v5@v5.0.8/mux.go:90 +0x2d8
net/http.serverHandler.ServeHTTP({0x103f69b28?}, {0x103f6fe60, 0x14001d14000}, 0x140000a6000)
	net/http/server.go:2947 +0x2c4
net/http.(*conn).serve(0x14000acc000, {0x103f71bc0, 0x14000a40c30})
	net/http/server.go:1991 +0x560
created by net/http.(*Server).Serve
	net/http/server.go:3102 +0x444
```

an example of how this pattern is used in graphql language client: https://github.com/jasonkuhrt/graphql-request/blob/main/examples/graphql-document-variables.ts

**Comment by orpheuslummis** [comment]
It is part of our query specification https://docs.source.network/references/query-specification/variables
