### ISSUE TITLE
Flaky Schema Migration `TestSchemaMigrationQueryMigratesAcrossMultipleVersions`

### ISSUE THREAD

**Issue by shahzadlone** [sourcenetwork/defradb#1745]
Saw this fail, thought to document it.

Failure run:
https://github.com/sourcenetwork/defradb/actions/runs/5733940558/job/15539365716?pr=1744

```
FAIL tests/integration/schema/migrations/query (-test.shuffle 1690943028255834496)
=== RUN   TestSchemaMigrationQueryMigratesAcrossMultipleVersions
2023-08-02T02:26:13.815Z, INFO, tests.integration, Test schema migration, across multiple migrated versions, {"Database": "badger-in-memory"}
2023-08-02T02:26:16.898Z, INFO, tests.integration, , {"RequestResults": [{"email":"ilovewasm@source.com","name":"John","verified":true}]}
2023-08-02T02:26:16.898Z, INFO, db, Closing DefraDB process...
2023-08-02T02:26:16.930Z, INFO, db, Successfully closed running process
2023-08-02T02:26:16.931Z, INFO, tests.integration, Test schema migration, across multiple migrated versions, {"Database": "badger-file-system"}
FAIL tests/integration/schema/migrations/query.TestSchemaMigrationQueryMigratesAcrossMultipleVersions (-1.00s)

=== Failed
=== FAIL: tests/integration/schema/migrations/query  (0.00s)
-test.shuffle 1690943028255834496
panic: test timed out after 2m30s
running tests:
	TestSchemaMigrationQueryMigratesAcrossMultipleVersions (4s)

goroutine 27988 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:2241 +0x219
created by time.goFunc
	/opt/hostedtoolcache/go/1.20.6/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0004864e0, {0x259c394, 0x36}, 0x2688c88)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1630 +0x82e
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:2036 +0x8e
testing.tRunner(0xc0004864e0, 0xc000c2fb48)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1576 +0x217
testing.runTests(0xc000704280?, {0x367cf80, 0x17, 0x17}, {0x2?, 0x4ad179?, 0x3902de0?})
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:2034 +0x87d
testing.(*M).Run(0xc000704280)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1906 +0xb45
main.main()
	_testmain.go:91 +0x2ea
```

**Comment by AndrewSisley** [comment]
I think this is just the whole package timing out, with wazero in, and more tests added recently, we need to bump up the timer again
