### ISSUE TITLE
Schema View: panics if query is recursive

### ISSUE THREAD

**Issue by islamaliev** [sourcenetwork/defradb#2190]
```go

func TestView_RecursiveQuery(t *testing.T) {
	test := testUtils.TestCase{
		Description: "One to many view with alias on inner object",
		Actions: []any{
			testUtils.SchemaUpdate{
				Schema: `
					type Author {
						name: String
						books: [Book]
					}
					type Book {
						name: String
						author: Author
					}
				`,
			},
			testUtils.CreateView{
				Query: `
					Book {
						name
						author {
							name
							books {
								name
								author {
									name
								}
							}
						}
					}
				`,
				SDL: `
					type BookView {
						name: String
						author: AuthorView
					}
					interface AuthorView {
						name: String
						books: [BookView]
					}
				`,
			},
			// bae-ef9cd756-08e1-5f23-abeb-7b3e6351a68d
			testUtils.CreateDoc{
				CollectionID: 0,
				Doc: `{
					"name":	"Harper Lee"
				}`,
			},
			testUtils.CreateDoc{
				CollectionID: 1,
				Doc: `{
					"name":	"To Kill a Mockingbird",
					"author_id": "bae-ef9cd756-08e1-5f23-abeb-7b3e6351a68d"
				}`,
			},
			testUtils.Request{
				Request: `
					query {
						BookView {
							name
						}
					}
				`,
			},
		},
	}

	testUtils.ExecuteTestCase(t, test)
}
```
Stacktrace:
```
anic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 6 [running]:
testing.tRunner.func1.2({0x104424cc0, 0x14000d24990})
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1529 +0x384
panic({0x104424cc0, 0x14000d24990})
	/Users/islam/sdk/go1.20.7/src/runtime/panic.go:884 +0x204
github.com/sourcenetwork/defradb/core.(*DocumentMapping).SetFirstOfName(...)
	/Users/islam/dev/sourcenetwork/defradb/core/doc.go:180
github.com/sourcenetwork/defradb/planner.(*viewNode).Value(0x140004c0b60)
	/Users/islam/dev/sourcenetwork/defradb/planner/view.go:72 +0x23c
github.com/sourcenetwork/defradb/planner.(*selectNode).Next(0x1400052c270)
	/Users/islam/dev/sourcenetwork/defradb/planner/select.go:157 +0x60
github.com/sourcenetwork/defradb/planner.(*selectTopNode).Next(0x140008a6d18?)
	/Users/islam/dev/sourcenetwork/defradb/planner/select.go:70 +0x28
github.com/sourcenetwork/defradb/planner.(*Planner).executeRequest(0x18?, {0x1041b1d40?, 0x140005f9b80?}, {0x104531ca0, 0x14000695c20})
	/Users/islam/dev/sourcenetwork/defradb/planner/planner.go:520 +0x48
github.com/sourcenetwork/defradb/planner.(*Planner).RunRequest(0x140004cc6c0?, {0x104525170, 0x14000196018}, 0x140005f9b80)
	/Users/islam/dev/sourcenetwork/defradb/planner/planner.go:575 +0x230
github.com/sourcenetwork/defradb/db.(*db).execRequest(0x140009368f0, {0x104525170?, 0x14000196018}, {0x103c7404c, 0x3e}, {0x1045355a8?, 0x1400045ae00})
	/Users/islam/dev/sourcenetwork/defradb/db/request.go:53 +0x3c8
github.com/sourcenetwork/defradb/db.(*implicitTxnDB).ExecRequest(0x140000101f0, {0x104525170, 0x14000196018}, {0x103c7404c, 0x3e})
	/Users/islam/dev/sourcenetwork/defradb/db/txn_db.go:45 +0x150
github.com/sourcenetwork/defradb/tests/integration.executeRequest(0x14000439340, {{0x0, 0x0}, {0x0, 0x0}, {0x103c7404c, 0x3e}, {0x0, 0x0, 0x0}, ...})
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:1528 +0x11c
github.com/sourcenetwork/defradb/tests/integration.performAction(0x14000439340?, 0x0?, {0x104435dc0?, 0x140005e71f0?})
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:306 +0x5bc
github.com/sourcenetwork/defradb/tests/integration.executeTestCase({0x104525170?, 0x14000196018}, 0x140008031e0, {0x14000146340, 0x2, 0x2}, {{0x103c59414, 0x2b}, {0x1400003ccd0, 0x5, ...}, ...}, ...)
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:205 +0x80c
github.com/sourcenetwork/defradb/tests/integration.ExecuteTestCase(0x104435dc0?, {{0x103c59414, 0x2b}, {0x1400003ccd0, 0x5, 0x5}, {0x0, {0x0, 0x0, 0x0}}})
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/utils2.go:161 +0x580
github.com/sourcenetwork/defradb/tests/integration/view/one_to_many.TestView_NotUsedNested(0x0?)
	/Users/islam/dev/sourcenetwork/defradb/tests/integration/view/one_to_many/with_alias_test.go:239 +0x2dc
testing.tRunner(0x140008031e0, 0x1045092c8)
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1576 +0x10c
created by testing.(*T).Run
	/Users/islam/sdk/go1.20.7/src/testing/testing.go:1629 +0x368
FAIL	github.com/sourcenetwork/defradb/tests/integration/view/one_to_many	0.879s
FAIL
```

**Comment by AndrewSisley** [comment]
Fixed by https://github.com/sourcenetwork/defradb/pull/2192
